# Generated by Django 5.2 on 2025-06-28 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='成就名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='地点')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就',
                'db_table': 'Achievement',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='BlogOwner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像URL')),
                ('github_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='GitHub链接')),
                ('github_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='GitHub用户名')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('identity', models.CharField(blank=True, max_length=100, null=True, verbose_name='身份')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
            ],
            options={
                'verbose_name': '博客所有者',
                'verbose_name_plural': '博客所有者',
                'db_table': 'BlogOwner',
            },
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('count', models.IntegerField(default=0, verbose_name='使用次数')),
            ],
            options={
                'verbose_name': '博客标签',
                'verbose_name_plural': '博客标签',
                'db_table': 'BlogTags',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='学校名称')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='学位')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
                'db_table': 'Education',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('count', models.IntegerField(default=0, verbose_name='使用次数')),
            ],
            options={
                'verbose_name': '项目标签',
                'verbose_name_plural': '项目标签',
                'db_table': 'ProjectTags',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=50, unique=True, verbose_name='设置键')),
                ('setting_value', models.TextField(verbose_name='设置值')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'SystemSettings',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '工作经验',
                'verbose_name_plural': '工作经验',
                'db_table': 'WorkExperience',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('cover_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='封面图片')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('views_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('featured', models.BooleanField(default=False, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'db_table': 'Blogs',
                'indexes': [models.Index(fields=['category'], name='Blogs_categor_b94b80_idx'), models.Index(fields=['published_at'], name='Blogs_publish_aaa219_idx'), models.Index(fields=['featured'], name='Blogs_feature_cf0b84_idx')],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(max_length=100, unique=True, verbose_name='GitHub ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('full_name', models.CharField(max_length=150, verbose_name='完整名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('owner', models.CharField(max_length=100, verbose_name='所有者')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='语言')),
                ('stars_count', models.IntegerField(default=0, verbose_name='星标数')),
                ('forks_count', models.IntegerField(default=0, verbose_name='分支数')),
                ('watchers_count', models.IntegerField(default=0, verbose_name='观察者数')),
                ('open_issues_count', models.IntegerField(default=0, verbose_name='开放问题数')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
                ('fetched_at', models.DateTimeField(verbose_name='获取时间')),
                ('trending_rank', models.IntegerField(blank=True, null=True, verbose_name='趋势排名')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'Projects',
                'indexes': [models.Index(fields=['trending_rank'], name='Projects_trendin_d98be9_idx'), models.Index(fields=['language'], name='Projects_languag_416f57_idx'), models.Index(fields=['stars_count'], name='Projects_stars_c_e4cca8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('proficiency', models.IntegerField(verbose_name='熟练度')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='类别')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'db_table': 'Skill',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['category'], name='Skill_categor_4529ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户代理')),
                ('visit_time', models.DateTimeField(verbose_name='访问时间')),
                ('page_url', models.CharField(max_length=255, verbose_name='页面URL')),
                ('referer', models.CharField(blank=True, max_length=255, null=True, verbose_name='来源')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
            ],
            options={
                'verbose_name': '访客',
                'verbose_name_plural': '访客',
                'db_table': 'Visitors',
                'indexes': [models.Index(fields=['visit_time'], name='Visitors_visit_t_b1a08b_idx'), models.Index(fields=['ip_address'], name='Visitors_ip_addr_d291db_idx'), models.Index(fields=['page_url'], name='Visitors_page_ur_845d1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogTagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.blogs', verbose_name='博客')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.blogtags', verbose_name='标签')),
            ],
            options={
                'verbose_name': '博客标签映射',
                'verbose_name_plural': '博客标签映射',
                'db_table': 'BlogTagMapping',
                'unique_together': {('blog', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, verbose_name='会话ID')),
                ('role', models.CharField(max_length=10, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('timestamp', models.DateTimeField(verbose_name='时间戳')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_api.projects', verbose_name='相关项目')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'ChatMessages',
                'indexes': [models.Index(fields=['session_id'], name='ChatMessage_session_75cd7c_idx'), models.Index(fields=['timestamp'], name='ChatMessage_timesta_2a4c68_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectTagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.projects', verbose_name='项目')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.projecttags', verbose_name='标签')),
            ],
            options={
                'verbose_name': '项目标签映射',
                'verbose_name_plural': '项目标签映射',
                'db_table': 'ProjectTagMapping',
                'unique_together': {('project', 'tag')},
            },
        ),
    ]
